In [1]:
import torch

In [2]:
torch.ones((2,), dtype=torch.int8)

tensor([1, 1], dtype=torch.int8)

In [4]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [11]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [10]:
torch.zeros((2,3)).dtype

torch.float32

In [16]:
torch.empty((2,3))

tensor([[2.5620e-01, 4.5773e-41, 2.5620e-01],
        [4.5773e-41, 4.4842e-44, 0.0000e+00]])

In [13]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [14]:
torch.full((2, 3), 3)

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [17]:
torch.rand((2,3))

tensor([[0.6714, 0.0930, 0.4395],
        [0.5943, 0.6582, 0.6573]])

In [20]:
torch.randint(10, 100, (2,3))

tensor([[63, 93, 68],
        [93, 58, 29]])

In [22]:
torch.randn((2,3))

tensor([[ 0.3470, -0.4741,  1.2870],
        [ 0.8544,  0.9717, -0.2017]])

In [25]:
torch.tensor([[1, 2 ,3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
torch.as_tensor([[1., 2 ,3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [30]:
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])

In [33]:
a.dtype

torch.int64

In [34]:
a.shape

torch.Size([2, 3])

In [35]:
b = torch.ones_like(a)

In [36]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [40]:
a.new_tensor([[0., 1.]])

tensor([[0, 1]])

In [50]:
a.new_full((2,2), 3.)

tensor([[3, 3],
        [3, 3]])