In [1]:
import torch
import torch.nn as nn

In [2]:
nn.Conv2d(3, 16, 3, padding=1)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [3]:
nn.Conv2d(3, 16, 3, stride=2, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 2))

In [4]:
nn.Conv2d(3, 16, (3,4), padding=1)

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 1))

In [5]:
nn.Conv2d(3, 16, (3,4), padding=(1,4))

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 4))

In [6]:
nn.Conv2d(3, 16, (3,4), stride=(3,3), padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [7]:
nn.Conv2d(3, 16, (3,4), stride=3, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [8]:
nn.Conv2d??

In [9]:
nn.Conv2d(3, 16, 3)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1))

In [10]:
nn.Conv2d(3, 16, 3, stride=2)

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2))

In [11]:
max_pool = nn.MaxPool2d(3, stride=1)

In [12]:
a = torch.FloatTensor(3,5,5).random_(0, 10)

In [13]:
a

tensor([[[0., 2., 0., 8., 8.],
         [0., 2., 4., 2., 4.],
         [9., 4., 3., 8., 2.],
         [8., 7., 9., 8., 8.],
         [5., 3., 9., 3., 2.]],

        [[6., 6., 8., 2., 6.],
         [5., 6., 6., 9., 1.],
         [4., 5., 0., 8., 4.],
         [3., 3., 9., 5., 1.],
         [8., 4., 8., 4., 1.]],

        [[2., 4., 2., 9., 3.],
         [5., 2., 0., 4., 4.],
         [1., 1., 3., 2., 0.],
         [3., 2., 1., 5., 0.],
         [4., 2., 8., 7., 2.]]])

In [14]:
max_pool(a)

tensor([[[9., 8., 8.],
         [9., 9., 9.],
         [9., 9., 9.]],

        [[8., 9., 9.],
         [9., 9., 9.],
         [9., 9., 9.]],

        [[5., 9., 9.],
         [5., 5., 5.],
         [8., 8., 8.]]])

In [15]:
avg_pool = nn.AvgPool2d(3, stride=1)

In [16]:
avg_pool(a)

tensor([[[2.6667, 3.6667, 4.3333],
         [5.1111, 5.2222, 5.3333],
         [6.3333, 6.0000, 5.7778]],

        [[5.1111, 5.5556, 4.8889],
         [4.5556, 5.6667, 4.7778],
         [4.8889, 5.1111, 4.4444]],

        [[2.2222, 3.0000, 3.0000],
         [2.0000, 2.2222, 2.1111],
         [2.7778, 3.4444, 3.1111]]])

In [19]:
from torchvision import datasets

In [1]:
from torchvision import transforms

/home/jibin/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [2]:
transforms.ToTensor()

ToTensor()

In [3]:
transforms.Resize(1)

Resize(size=1, interpolation=PIL.Image.BILINEAR)

In [4]:
transforms.Resize((1,1))

Resize(size=(1, 1), interpolation=PIL.Image.BILINEAR)

In [8]:
transforms.Pad(1, 0)

Pad(padding=1, fill=0, padding_mode=constant)

In [9]:
transforms.Pad((1, 2), 1)

Pad(padding=(1, 2), fill=1, padding_mode=constant)

In [14]:
transforms.Pad((1, 2, 2, 3), padding_mode='reflect')

Pad(padding=(1, 2, 2, 3), fill=0, padding_mode=reflect)

In [15]:
transforms.Normalize((0.5,),(0.5,))

Normalize(mean=(0.5,), std=(0.5,))

In [12]:
transforms.Compose([
     transforms.CenterCrop(10),
     transforms.ToTensor(),
])

Compose(
    CenterCrop(size=(10, 10))
    ToTensor()
)

In [5]:
transforms.CenterCrop(10)

CenterCrop(size=(10, 10))

In [ ]:
train_data = datasets.CIFAR10('data', train=True, download=True, transform=transform)