In [1]:
import torch
import torch.nn as nn

In [20]:
nn.Conv2d(3, 16, 3, padding=1)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))

In [21]:
nn.Conv2d(3, 16, 3, stride=2, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 2))

In [11]:
nn.Conv2d(3, 16, (3,4), padding=1)

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 1))

In [14]:
nn.Conv2d(3, 16, (3,4), padding=(1,4))

Conv2d(3, 16, kernel_size=(3, 4), stride=(1, 1), padding=(1, 4))

In [17]:
nn.Conv2d(3, 16, (3,4), stride=(3,3), padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [18]:
nn.Conv2d(3, 16, (3,4), stride=3, padding=(1,2))

Conv2d(3, 16, kernel_size=(3, 4), stride=(3, 3), padding=(1, 2))

In [27]:
nn.Conv2d??

In [22]:
nn.Conv2d(3, 16, 3)

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1))

In [23]:
nn.Conv2d(3, 16, 3, stride=2)

Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2))

In [11]:
max_pool = nn.MaxPool2d(3, stride=1)

In [12]:
a = torch.FloatTensor(3,5,5).random_(0, 10)

In [13]:
a

tensor([[[2., 8., 6., 8., 3.],
         [6., 6., 7., 6., 6.],
         [2., 0., 8., 8., 8.],
         [2., 0., 3., 5., 7.],
         [9., 7., 8., 2., 1.]],

        [[1., 8., 6., 7., 3.],
         [0., 1., 2., 9., 4.],
         [1., 2., 5., 0., 1.],
         [8., 2., 8., 3., 1.],
         [5., 4., 0., 5., 2.]],

        [[1., 6., 2., 6., 1.],
         [4., 0., 0., 6., 6.],
         [4., 2., 2., 3., 2.],
         [1., 0., 1., 7., 1.],
         [8., 1., 0., 5., 4.]]])

In [14]:
max_pool(a)

tensor([[[8., 8., 8.],
         [8., 8., 8.],
         [9., 8., 8.]],

        [[8., 9., 9.],
         [8., 9., 9.],
         [8., 8., 8.]],

        [[6., 6., 6.],
         [4., 7., 7.],
         [8., 7., 7.]]])

In [15]:
avg_pool = nn.AvgPool2d(3, stride=1)

In [16]:
avg_pool(a)

tensor([[[5.0000, 6.3333, 6.6667],
         [3.7778, 4.7778, 6.4444],
         [4.3333, 4.5556, 5.5556]],

        [[2.8889, 4.4444, 4.1111],
         [3.2222, 3.5556, 3.6667],
         [3.8889, 3.2222, 2.7778]],

        [[2.3333, 3.0000, 3.1111],
         [1.5556, 2.3333, 3.1111],
         [2.1111, 2.3333, 2.7778]]])