In [2]:
import torch

In [3]:
torch.ones((2,), dtype=torch.int8)

tensor([1, 1], dtype=torch.int8)

In [4]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [6]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [7]:
torch.zeros((2,3)).dtype

torch.float32

In [8]:
torch.empty((2,3))

tensor([[0.0000e+00, 0.0000e+00, 7.2646e+22],
        [7.2250e+28, 2.5226e-18, 2.4283e-18]])

In [9]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [10]:
torch.full((2, 3), 3)

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [11]:
torch.rand((2,3))

tensor([[0.3088, 0.3042, 0.5855],
        [0.0776, 0.7097, 0.6423]])

In [12]:
torch.randint(10, 100, (2,3))

tensor([[77, 11, 37],
        [82, 78, 83]])

In [13]:
torch.randn((2,3))

tensor([[-1.8856, -0.4864, -0.6250],
        [-0.2469,  0.1903, -1.4959]])

In [14]:
torch.tensor([[1, 2 ,3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.as_tensor([[1., 2 ,3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])

In [17]:
a.dtype

torch.int64

In [18]:
a.shape

torch.Size([2, 3])

In [19]:
b = torch.ones_like(a)

In [20]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
a.new_tensor([[0., 1.]])

tensor([[0, 1]])

In [22]:
a.new_full((2,2), 3.)

tensor([[3, 3],
        [3, 3]])

In [24]:
a.size()

torch.Size([2, 3])

In [26]:
a.dtype

torch.int64

In [27]:
b.numel()

6

In [28]:
import numpy as np
a = np.random.rand(2,3)
a

array([[0.8382881 , 0.7013574 , 0.13261772],
       [0.07342714, 0.03446181, 0.67762371]])

In [33]:
a = np.ones((2, 3))

In [34]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
b = torch.from_numpy(a)

In [36]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)